### ISSUE TITLE
Crash after matchmaking for a bit

### ISSUE THREAD

**Issue by gausie** [crockpotveggies/tinderbox#2] opened 2015-02-10 10:20 UTC
Getting this trace:

```
[ERROR] [02/10/2015 10:19:18.195] [application-akka.actor.default-dispatcher-5] [LocalActorRefProvider(akka://application)] guardian failed, shutting down system
java.io.IOError: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:860)
	at org.mapdb.Volume.getUnsignedShort(Volume.java:91)
	at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1077)
	at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:944)
	at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1063)
	at org.mapdb.StoreWAL.longStackPut(StoreWAL.java:989)
	at org.mapdb.StoreDirect.freePhysPut(StoreDirect.java:1055)
	at org.mapdb.StoreWAL.update(StoreWAL.java:425)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.UpdatesService$$anonfun$services$UpdatesService$$syncUpdates$6.apply(UpdatesService.scala:111)
	at services.UpdatesService$$anonfun$services$UpdatesService$$syncUpdates$6.apply(UpdatesService.scala:111)
	at scala.Option.map(Option.scala:145)
	at services.UpdatesService$.services$UpdatesService$$syncUpdates(UpdatesService.scala:111)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1.applyOrElse(UpdatesService.scala:49)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:807)
	at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:857)
	... 31 more

[ERROR] [02/10/2015 10:19:18.195] [application-akka.actor.default-dispatcher-5] [akka://application/user] java.io.EOFException
java.io.IOError: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:860)
	at org.mapdb.Volume.getUnsignedShort(Volume.java:91)
	at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1077)
	at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:944)
	at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1063)
	at org.mapdb.StoreWAL.longStackPut(StoreWAL.java:989)
	at org.mapdb.StoreDirect.freePhysPut(StoreDirect.java:1055)
	at org.mapdb.StoreWAL.update(StoreWAL.java:425)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.UpdatesService$$anonfun$services$UpdatesService$$syncUpdates$6.apply(UpdatesService.scala:111)
	at services.UpdatesService$$anonfun$services$UpdatesService$$syncUpdates$6.apply(UpdatesService.scala:111)
	at scala.Option.map(Option.scala:145)
	at services.UpdatesService$.services$UpdatesService$$syncUpdates(UpdatesService.scala:111)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1$$anonfun$applyOrElse$1.apply(UpdatesService.scala:49)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at services.UpdatesService$UpdatesTask$$anonfun$receive$1.applyOrElse(UpdatesService.scala:49)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:807)
	at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:857)
	... 31 more
```

**Comment by crockpotveggies** [comment] 2015-02-10 16:23
It looks like a bug in MapDB, check out this issue here https://github.com/jankotek/MapDB/issues/163. Unfortunately, wouldn't have a quick fix for this.

**Comment by crockpotveggies** [comment] 2015-02-11 19:36
Added this to the Wiki. Going to close it for now.

**Closed by crockpotveggies** 2015-02-11 19:36 UTC

**Comment by matthewleonard** [comment] 2015-02-18 15:31
[warn] application - [recommendations] Could not yet build face models for user 546d905e51feb5a849fc6841 because:
java.io.IOError: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.getLong(Volume.java:837)
	at org.mapdb.StoreDirect.getLinkedRecordsIndexVals(StoreDirect.java:644)
	at org.mapdb.StoreWAL.update(StoreWAL.java:415)
	at org.mapdb.Caches$HashTable.update(Caches.java:269)
	at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
	at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
	at org.mapdb.BTreeMap.put(BTreeMap.java:643)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:225)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1$$anonfun$applyOrElse$5.apply(FacialAnalysisService.scala:219)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at services.FacialAnalysisService$FaceAnalysisTask$$anonfun$receive$1.applyOrElse(FacialAnalysisService.scala:219)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:807)
	at org.mapdb.Volume$FileChannelVol.getLong(Volume.java:834)
	... 19 more

[warn] application - [tinderbot] TinderBot is under pressure (tasks queue > 500)
[warn] application - [tinderbot] TinderBot is under pressure (tasks queue > 500)
[debug] application - [mapdb] Database committer has persisted data to disk.
[warn] application - [tinderbot] TinderBot is under pressure (tasks queue > 500)

**Comment by matthewleonard** [comment] 2015-02-18 15:43
A slightly different EOF:
play.api.Application$$anon$1: Execution exception[[ExecutionException: Boxed Error]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10-2.2.2.jar:2.2.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.4.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.4.jar:na]
Caused by: java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:55) ~[scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47) ~[scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244) [scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [scala-library-2.10.4.jar:na]
Caused by: java.io.IOError: java.io.EOFException
	at org.mapdb.Volume$FileChannelVol.getDataInput(Volume.java:871) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.Volume$FileChannelVol.getDataInput(Volume.java:641) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreDirect.get2(StoreDirect.java:458) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreWAL.get2(StoreWAL.java:368) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreWAL.get(StoreWAL.java:352) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.Caches$HashTable.get(Caches.java:245) ~[mapdb-1.0.6.jar:na]
Caused by: java.io.EOFException: null
	at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:807) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.Volume$FileChannelVol.getDataInput(Volume.java:868) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.Volume$FileChannelVol.getDataInput(Volume.java:641) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreDirect.get2(StoreDirect.java:458) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreWAL.get2(StoreWAL.java:368) ~[mapdb-1.0.6.jar:na]
	at org.mapdb.StoreWAL.get(StoreWAL.java:352) ~[mapdb-1.0.6.jar:na]

**Comment by alextavgen** [comment] 2015-03-02 11:53
Hi,
Such a error can be showed up, when  there was  incorrectly interrupted flaw of the program in time it writes data to the disk. For example I tested it on Windows, and if you have an crash of JVM in the time data were persisted to the disk, you will have a EOF Exceptions, because data which was persisted to the disk was a corrupted. Just remove old data, from /data folder, and you will have a correctly working system.

**Comment by alextavgen** [comment] 2015-03-02 11:54
Hi,
Such a error can be showed up, when  there was  incorrectly interrupted flaw of the program in time it writes data to the disk. For example I tested it on Windows, and if you have an crash of JVM in the time data were persisted to the disk, you will have a EOF Exceptions, because data which was persisted to the disk was a corrupted. Just remove old data, from /data folder, and you will have a correctly working system.

**Comment by alextavgen** [comment] 2015-03-02 11:55
Hi,
Such a error can be showed up, when  there was  incorrectly interrupted flaw of the program in time it writes data to the disk. For example I tested it on Windows, and if you have an crash of JVM in the time data were persisted to the disk, you will have a EOF Exceptions, because data which was persisted to the disk was a corrupted. Just remove old data, from /data folder, and you will have a correctly working system.
