### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$

### ISSUE THREAD

**Issue by matthewleonard** [crockpotveggies/tinderbox#40] opened 2015-02-18 15:38 UTC
Console after running "sbt -mem:2048 run":

[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] Starting new facial check task.
Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$
	at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [02/18/2015 07:37:25.984] [application-akka.actor.default-dispatcher-3] [ActorSystem(application)] Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$
	at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by crockpotveggies** [comment] 2015-02-18 16:32
Tinderbox has actually been updated to run without SBT (since it had a lot of unintended side effects). You can start it up using the new scripts or Dock icon, the wiki has been updated.

Are you using SBT for dev reasons?

**Comment by matthewleonard** [comment] 2015-02-19 04:09
I ran it with the new scripts and see the same error. Let me know if I should wipe/clear the currently built data set, would be happy to test.

**Comment by crockpotveggies** [comment] 2015-02-19 15:29
Strange. I'm not sure I have a solution, since for some reason the JVM can't find the FacialAnalysisService class in the Class Loader. It looks localized to your particular machine. Can you check your Java version?  Run both commands `java -version` and `javac -version` and please paste the contents in this issue. Going to close it since it looks localized, but will still try to help.

For example...
```
justin$ java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)
```

**Closed** 2015-02-19 15:29 UTC

**Comment by 0xc1c4da** [comment] 2015-12-23 00:39
Ran into this issue also, running from tinderbox.app

tinderbox git:master ❯ java -version                                                                                                         ⏎ ✹
Picked up _JAVA_OPTIONS: -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Xms1024m -Xmx2G -Xss256m -XX:MaxPermSize=4G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=4G; support was removed in 8.0
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

tinderbox git:master ❯ javac -version                                                                                                          ✹
Picked up _JAVA_OPTIONS: -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Xms1024m -Xmx2G -Xss256m -XX:MaxPermSize=4G
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=4G; support was removed in 8.0
javac 1.8.0_40

[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[debug] application - [mapdb] Database committer has persisted data to disk.
[debug] application - [tinderbot] created new Facial Check task for token e59c3c48-60cd-434c-bda9-6f40303cef56
[debug] application - [tinderbot] created new Recommendation task for token e59c3c48-60cd-434c-bda9-6f40303cef56
[debug] application - [tinderbot] New task received for supervision
[debug] application - [tinderbot] created new Message Analysis task for token e59c3c48-60cd-434c-bda9-6f40303cef56
[info] application - [tinderbot] Received command: idle
[debug] application - [tinderbot] Starting new facial check task.
[info] application - Creating new session for xAuthToken f68bb938-7bc7-4585-8389-03bd7cb26ff5
java.lang.NoClassDefFoundError: Could not initialize class services.FacialAnalysisService$
    at controllers.FacialAnalysis$$anonfun$checkModelValidity$1$$anonfun$apply$3.apply(FacialAnalysis.scala:65)
    at controllers.FacialAnalysis$$anonfun$checkModelValidity$1$$anonfun$apply$3.apply(FacialAnalysis.scala:61)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
    at scala.util.Try$.apply(Try.scala:161)
    at scala.util.Success.map(Try.scala:206)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.ExceptionInInitializerError
    at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    at akka.actor.ActorCell.invoke(ActorCell.scala:456)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Could not instantiate class
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
    at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
    at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:449)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
    at org.mapdb.Store.deserialize(Store.java:297)
    at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
    at org.mapdb.StoreWAL.get(StoreWAL.java:320)
    at org.mapdb.Caches$HashTable.get(Caches.java:246)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
    at org.mapdb.DB.getTreeMap(DB.java:805)
    at services.FacialAnalysisService$.<init>(FacialAnalysisService.scala:45)
    at services.FacialAnalysisService$.<clinit>(FacialAnalysisService.scala)
    ... 10 more
Caused by: java.io.OptionalDataException
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1371)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at scala.collection.mutable.HashMap$$anonfun$readObject$1.apply(HashMap.scala:142)
    at scala.collection.mutable.HashMap$$anonfun$readObject$1.apply(HashMap.scala:142)
    at scala.collection.mutable.HashTable$class.init(HashTable.scala:105)
    at scala.collection.mutable.HashMap.init(HashMap.scala:39)
    at scala.collection.mutable.HashMap.readObject(HashMap.scala:142)
[ERROR] [12/22/2015 16:36:30.672] [application-akka.actor.default-dispatcher-3] [ActorSystem(application)] Uncaught error from thread [application-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.ExceptionInInitializerError
    at models.bot.tasks.FacialCheckTask$$anonfun$receive$1.applyOrElse(FacialCheckTask.scala:50)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    at akka.actor.ActorCell.invoke(ActorCell.scala:456)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    at akka.dispatch.Mailbox.run(Mailbox.scala:219)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Could not instantiate class
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:483)
    at org.mapdb.SerializerBase.deserialize3(SerializerBase.java:1216)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:1132)
    at org.mapdb.SerializerBase.deserialize(SerializerBase.java:867)
    at org.mapdb.SerializerPojo.deserialize(SerializerPojo.java:701)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:449)
    at org.mapdb.BTreeMap$NodeSerializer.deserialize(BTreeMap.java:288)
    at org.mapdb.Store.deserialize(Store.java:297)
    at org.mapdb.StoreDirect.get2(StoreDirect.java:486)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
    at org.mapdb.StoreWAL.get(StoreWAL.java:320)
    at org.mapdb.Caches$HashTable.get(Caches.java:246)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.<init>(BTreeMap.java:541)
    at org.mapdb.DB.getTreeMap(DB.java:805)
    at services.FacialAnalysisService$.<init>(FacialAnalysisService.scala:45)
    at services.FacialAnalysisService$.<clinit>(FacialAnalysisService.scala)
    ... 10 more
Caused by: java.io.OptionalDataException
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1371)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at scala.collection.mutable.HashMap$$anonfun$readObject$1.apply(HashMap.scala:142)
    at scala.collection.mutable.HashMap$$anonfun$readObject$1.apply(HashMap.scala:142)
    at scala.collection.mutable.HashTable$class.init(HashTable.scala:105)
    at scala.collection.mutable.HashMap.init(HashMap.scala:39)
    at scala.collection.mutable.HashMap.readObject(HashMap.scala:142)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:461)
    ... 26 more
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
at org.mapdb.SerializerPojo.deserializeUnknownHeader(SerializerPojo.java:461)
... 26 more
```

java.lang.ExceptionInInitializerError
    at controllers.Analytics$$anonfun$messageSentiments$1$$anonfun$1.apply(Analytics.scala:19)
    at controllers.Analytics$$anonfun$messageSentiments$1$$anonfun$1.apply(Analytics.scala:19)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[info] play - Shutdown application default Akka system.
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
    at org.mapdb.StoreDirect.get2(StoreDirect.java:451)
    at org.mapdb.StoreWAL.get2(StoreWAL.java:336)
    at org.mapdb.StoreWAL.get(StoreWAL.java:320)
    at org.mapdb.Caches$HashTable.get(Caches.java:246)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.<init>(BTreeMap.java:539)
    at org.mapdb.DB.getTreeMap(DB.java:805)
    at services.AnalyticsService$.<init>(AnalyticsService.scala:29)
    at services.AnalyticsService$.<clinit>(AnalyticsService.scala)
    ... 9 more
java.lang.NoClassDefFoundError: Could not initialize class services.UpdatesService$
    at controllers.Messaging$$anonfun$messageSummaries$1$$anonfun$5.apply(Messaging.scala:36)
    at controllers.Messaging$$anonfun$messageSummaries$1$$anonfun$5.apply(Messaging.scala:36)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.IllegalAccessError: already closed
    at org.mapdb.EngineWrapper$1.get(EngineWrapper.java:472)
    at org.mapdb.EngineWrapper.get(EngineWrapper.java:58)
    at org.mapdb.BTreeMap.get(BTreeMap.java:595)
    at org.mapdb.BTreeMap.get(BTreeMap.java:589)
    at org.mapdb.DB.catGet(DB.java:93)
    at org.mapdb.DB.getTreeMap(DB.java:791)
    at services.UpdatesService$.<init>(UpdatesService.scala:33)
    at services.UpdatesService$.<clinit>(UpdatesService.scala)
    at controllers.Messaging$$anonfun$messageSummaries$1$$anonfun$1.apply$mcV$sp(Messaging.scala:35)
    at controllers.Messaging$$anonfun$messageSummaries$1$$anonfun$1.apply(Messaging.scala:35)
    at controllers.Messaging$$anonfun$messageSummaries$1$$anonfun$1.apply(Messaging.scala:35)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO] [12/22/2015 16:36:30.693] [application-akka.actor.default-dispatcher-7] [akka://application/user/TinderBot] Message [models.bot.BotCommand] from Actor[akka://application/user/TinderBot/BotSupervisor/$a#1755558843] to Actor[akka://application/user/TinderBot#-1291105060] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
